### PR TITLE
Simplied the Profile page and made it a bit nicer

### PR DESCRIPTION
**Pull request by atombrain**
Also updated some whitespace issues on the Profile page.

### CODE REVIEW

**Comment by atombrain** [comment]
armsProfilePage

**Comment by RobertCochran** [comment]
Very nice!

Something though that looks like is absent in the redesign is being able to feed in a profile dump into the tool so that the user doesn't have to refill all of the fields by hand if they want to change any single one. That's something we're going to need to figure out for usability reasons.

The way it is currently designed, the website and bot are entirely separate, so this precludes the website from being able to simply fill in the data given a Discord ID. If we can figure out an alternative means of supplying that functionality, then by all means, we can do whatever that approach is. But for now, I think we need to keep the input text box (which you can have be automatically updated if you want, that's actually a pretty neat feature).

**Comment by atombrain** [comment]
Gotcha.  What if we made the textarea that holds the JSON data dump also be kept in sync with the form fields?  Meaning if any changes are made in the textarea (like pasting a dump you got from a Discord bot command) all of the form fields are automatically filled in.  Then the user can change the form fields (causing the JSON data dump in the textarea to get updated) and copy/paste the JSON data back into Discord.  We'd have to figure out a way to communicate this functionality on the page somehow, but I think it satisfies what you're after.

**Comment by atombrain** [comment]
Thinking about this a bit more, and I think you're right.  Probably need something that clearly communicates the different intent of filling in the form from Discord data vs. dumping a command to run in Discord.

BTW, what will the Itembot command be that a user runs in Discord to get their JSON data dump?  Thinking about putting that somewhere on this profile page.

**Comment by atombrain** [comment]
Think I figured out a way to reasonably do it.  I'm borrowing from what the Randomizer page does to give the user 2 different modes.  Please take a look at the attached screenshots.

armsProfilePageStartFromScratch

armsProfilePageEditExisting

**Pull request merged**
